create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

create table if not exists public.tickers (
  symbol text primary key,
  company text not null,
  sector text,
  is_default boolean not null default false,
  priority integer not null default 100
);

create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  symbol text not null references public.tickers(symbol) on delete cascade,
  price numeric, change_abs numeric, change_pct numeric,
  day_open numeric, day_high numeric, day_low numeric, prev_close numeric,
  prev_day_high numeric, prev_day_low numeric,
  premarket_price numeric, premarket_change_pct numeric, premarket_high numeric, premarket_low numeric,
  volume bigint, avg_volume bigint, rel_volume numeric, vwap numeric,
  sma20 numeric, sma50 numeric, sma200 numeric, support numeric, resistance numeric,
  gap_pct numeric, atr numeric, iv numeric, iv_rank numeric, iv_percentile numeric, iv_change numeric,
  call_volume bigint, put_volume bigint, put_call_ratio numeric, total_oi bigint,
  unusual_options_volume boolean, momentum_score numeric, trend text,
  source_name text, source_type text, published_at timestamptz, retrieved_at timestamptz not null default now(),
  confidence numeric, is_demo boolean not null default true, as_of timestamptz not null default now()
);
create index if not exists quotes_symbol_asof_idx on public.quotes(symbol, as_of desc);

create table if not exists public.market_snapshots (
  id bigint generated by default as identity primary key,
  as_of timestamptz not null default now(), regime text not null default 'Mixed', regime_note text,
  spy_price numeric, spy_change_pct numeric, spy_trend text,
  qqq_price numeric, qqq_change_pct numeric, qqq_trend text,
  iwm_price numeric, iwm_change_pct numeric, vix numeric, vix_change_pct numeric,
  dxy numeric, us10y numeric, us02y numeric, wti numeric, gold numeric,
  breadth_advancers integer, breadth_decliners integer, breadth_note text,
  sector_performance jsonb, macro_note text, market_status text,
  retrieved_at timestamptz not null default now(), is_demo boolean not null default true
);

create table if not exists public.market_movers (
  id bigint generated by default as identity primary key,
  symbol text not null, company text, kind text not null, value numeric, detail text,
  as_of timestamptz not null default now(), source_name text
);

create table if not exists public.analysis_runs (
  id bigint generated by default as identity primary key,
  run_id uuid not null default gen_random_uuid(), kind text not null, trading_day date not null default current_date,
  signals_generated integer not null default 0, updates_emitted integer not null default 0, feed_events integer not null default 0,
  regime text, notes text, started_at timestamptz not null default now(), finished_at timestamptz
);

create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  run_id uuid not null,
  symbol text not null,
  trading_day date not null default current_date,
  direction text not null default 'neutral', strategy text not null default 'watch',
  confidence_score numeric not null default 0, opportunity_score numeric not null default 0, risk_level text not null default 'Moderate',
  holding_period text, catalyst_summary text, no_trade_reason text,
  stock_price_at_generation numeric, suggested_expiration date, suggested_strike numeric, break_even numeric,
  est_premium numeric, max_defined_loss numeric, target_price numeric, invalidation_level numeric, expected_move_pct numeric,
  score_breakdown jsonb not null default '{}'::jsonb, weights jsonb not null default '{}'::jsonb,
  regime text, regime_explanation text, engine_version text not null default 'independent-1',
  is_demo boolean not null default true, generated_at timestamptz not null default now()
);
create index if not exists signals_symbol_generated_idx on public.signals(symbol, generated_at desc);

create or replace function public.prevent_signal_mutation() returns trigger language plpgsql as $$
begin raise exception 'signals are immutable'; end $$;
drop trigger if exists signals_immutable_update on public.signals;
create trigger signals_immutable_update before update or delete on public.signals for each row execute function public.prevent_signal_mutation();

create table if not exists public.contract_candidates (
  id bigint generated by default as identity primary key,
  signal_id bigint not null references public.signals(id) on delete cascade,
  profile text not null default 'Balanced', rank integer not null default 1, symbol text not null,
  option_type text not null, strike numeric not null, expiration date not null,
  bid numeric, ask numeric, mid numeric, volume bigint, open_interest bigint, implied_volatility numeric,
  delta numeric, gamma numeric, theta numeric, vega numeric, spread_pct numeric, liquidity_score numeric,
  selection_score numeric, break_even numeric, est_premium numeric, max_loss numeric, target_value numeric,
  prob_thesis_pct numeric, tradeoff text, flags jsonb not null default '[]'::jsonb
);

create table if not exists public.risk_assessments (
  id bigint generated by default as identity primary key,
  signal_id bigint not null unique references public.signals(id) on delete cascade,
  bull_case text, base_case text, bear_case text, premium_at_risk numeric, break_even numeric,
  theta_per_day numeric, iv_risk text, liquidity_risk text, catalyst_risk text,
  expected_move_pct numeric, time_remaining text, invalidation_level numeric,
  why_it_could_fail jsonb not null default '[]'::jsonb
);

create table if not exists public.news_items (
  id bigint generated by default as identity primary key,
  symbol text, headline text not null, summary text, category text, url text,
  source_name text not null, source_type text not null, sentiment text, sentiment_score numeric,
  impact text, recency_weight numeric, confidence numeric,
  published_at timestamptz not null, retrieved_at timestamptz not null default now(), is_demo boolean not null default true
);
create index if not exists news_symbol_published_idx on public.news_items(symbol, published_at desc);

create table if not exists public.filings (
  id bigint generated by default as identity primary key,
  symbol text, form_type text not null, title text, summary text, url text,
  source_name text not null, source_type text not null, filed_at timestamptz not null,
  retrieved_at timestamptz not null default now(), confidence numeric
);

create table if not exists public.transcript_statements (
  id bigint generated by default as identity primary key,
  symbol text not null, speaker text not null, speaker_role text, event_name text,
  quote text not null, why_it_matters text, market_impact text,
  source_name text not null, source_type text not null, source_url text,
  said_at timestamptz not null, retrieved_at timestamptz not null default now(), confidence numeric
);

create table if not exists public.sentiment_readings (
  id bigint generated by default as identity primary key,
  symbol text not null, cohort text not null, label text not null, score numeric,
  mention_volume bigint, sources jsonb not null default '[]'::jsonb, note text,
  source_type text not null, as_of timestamptz not null, retrieved_at timestamptz not null default now(), confidence numeric
);

create table if not exists public.economic_events (
  id bigint generated by default as identity primary key,
  title text not null, category text not null, event_time timestamptz not null,
  impact text not null, affected_symbols jsonb not null default '[]'::jsonb, detail text,
  source_name text not null, source_type text not null, source_url text, retrieved_at timestamptz not null default now()
);

create table if not exists public.earnings_events (
  id bigint generated by default as identity primary key,
  symbol text not null, report_time timestamptz not null, session text, confirmed boolean,
  eps_estimate numeric, revenue_estimate text, expected_move_pct numeric, source_name text not null, source_url text
);

create table if not exists public.signal_updates (
  id bigint generated by default as identity primary key,
  symbol text not null, signal_id bigint references public.signals(id) on delete set null,
  prev_direction text, prev_score numeric, new_direction text, new_score numeric,
  reason text not null, materiality text, created_at timestamptz not null default now()
);

create table if not exists public.signal_feed_events (
  id bigint generated by default as identity primary key,
  symbol text, category text not null, message text not null,
  source_name text not null, source_type text not null, source_url text,
  severity text, event_time timestamptz not null default now()
);


create table if not exists public.ohlcv_bars (
  id bigint generated by default as identity primary key,
  symbol text not null, timeframe text not null default '1d', bar_time timestamptz not null,
  open numeric not null, high numeric not null, low numeric not null, close numeric not null, volume bigint not null default 0,
  source_name text, retrieved_at timestamptz not null default now(), unique(symbol, timeframe, bar_time)
);

create table if not exists public.provider_configs (
  id bigint generated by default as identity primary key,
  provider_key text unique not null, interface_name text not null, display_name text not null,
  adapter text not null, mode text not null default 'demo', supplies jsonb not null default '[]'::jsonb,
  candidate_providers jsonb not null default '[]'::jsonb, secret_env_name text, docs_url text, notes text,
  last_sync timestamptz, last_error text
);

create table if not exists public.user_prefs (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text, alert_min_score numeric not null default 70,
  alert_directions text[] not null default array['bullish','bearish'], alert_risk_max text not null default 'High',
  alert_email boolean not null default false, auto_paper_trade boolean not null default false,
  explanation_level text not null default 'BALANCED', created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
drop trigger if exists user_prefs_set_updated_at on public.user_prefs;
create trigger user_prefs_set_updated_at before update on public.user_prefs for each row execute function public.set_updated_at();

create table if not exists public.watchlists (
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null, added_at timestamptz not null default now(), primary key(user_id, symbol)
);

create table if not exists public.paper_trades (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  signal_id bigint references public.signals(id) on delete set null,
  symbol text not null, direction text, strategy text, setup text, option_type text, strike numeric, expiration date,
  option_symbol text, asset_type text, broker text, account_label text, contracts integer not null default 1,
  position_size numeric, entry_at timestamptz default now(), entry_price numeric, exit_at timestamptz, exit_price numeric,
  fees numeric, realized_pl numeric, unrealized_pl numeric, origin text, regime text,
  signal_timestamp timestamptz, stock_price_at_generation numeric, contract_price_at_generation numeric,
  opportunity_score numeric, confidence_score numeric, risk_level text,
  thesis_id bigint, trade_plan_id bigint, intended_invalidation numeric, intended_target numeric,
  entry_assumptions text, max_favorable_excursion numeric, max_adverse_excursion numeric,
  closing_price numeric, result text not null default 'open', return_pct numeric, closed_at timestamptz,
  session_date date default current_date, was_planned boolean, process_adherence numeric,
  is_synthetic boolean default false, synthetic_profile text, is_demo boolean default true, notes text,
  created_at timestamptz not null default now()
);
create index if not exists paper_trades_user_created_idx on public.paper_trades(user_id, created_at desc);

create table if not exists public.trade_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  signal_id bigint references public.signals(id) on delete set null,
  symbol text not null, setup text, direction text, strategy text, opportunity_score numeric, confidence_score numeric,
  market_regime text, catalyst text, technical_evidence text, contract_label text,
  intended_entry_low numeric, intended_entry_high numeric, intended_invalidation numeric, intended_target numeric,
  expected_move_pct numeric, risk_level text, intended_position_size numeric, intended_contracts integer,
  origin text not null default 'self-originated', is_synthetic boolean not null default false,
  engine_version text not null default 'independent-1', created_at timestamptz not null default now()
);

create table if not exists public.trade_modifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  trade_id bigint references public.paper_trades(id) on delete cascade,
  trade_plan_id bigint references public.trade_plans(id) on delete cascade,
  modification_type text not null, field_changed text, previous_value text, new_value text,
  rationale text, deviation_type text, occurred_at timestamptz not null default now(),
  engine_version text not null default 'independent-1'
);

create table if not exists public.behavioral_observations (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  observation_type text not null, category text not null, statement text not null,
  baseline_value numeric, current_value numeric, deviation_pct numeric, unit text not null default '',
  sample_size integer not null default 0, observation_period text not null default '', confidence_label text not null default 'LOW',
  construct_key text, evidence_trade_ids bigint[] not null default '{}', severity text not null default 'LOW',
  model_version text not null default 'independent-1', session_date date, trade_id bigint references public.paper_trades(id) on delete set null,
  formula text not null default '', created_at timestamptz not null default now()
);

create table if not exists public.behavioral_prefs (
  user_id uuid primary key references auth.users(id) on delete cascade,
  onboarded boolean not null default false, consented boolean not null default false,
  categories jsonb not null default '{}'::jsonb, sensitivity text not null default 'STANDARD',
  entitlement text not null default 'trader_intelligence_beta', updated_at timestamptz not null default now()
);

create table if not exists public.usage_costs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  cost_type text not null, units numeric not null default 0, detail text, created_at timestamptz not null default now()
);

create table if not exists public.ai_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  thread text not null default 'main', role text not null, content text not null,
  context_used jsonb, symbol text, created_at timestamptz not null default now()
);

create table if not exists public.lit_constructs (
  id bigint generated by default as identity primary key,
  construct_key text unique not null, name text not null, plain_definition text not null,
  matador_operationalization text not null, variables_required text not null,
  min_sample integer not null default 0, confidence_requirement text not null default '', evidence_grade text not null default '',
  known_limitations text, layer text not null default 'behavioral'
);

create table if not exists public.lit_studies (
  id bigint generated by default as identity primary key,
  study_key text unique not null, title text not null, authors text not null, year integer not null,
  source text not null, doi text, doi_status text not null default 'unverified', evidence_type text not null default '',
  population_studied text not null default '', known_limitations text not null default '', finding_summary text not null default ''
);

create table if not exists public.lit_construct_studies (
  construct_key text not null references public.lit_constructs(construct_key) on delete cascade,
  study_key text not null references public.lit_studies(study_key) on delete cascade,
  relation text not null, note text, primary key(construct_key, study_key)
);

create table if not exists public.crm_contacts (
  id bigint generated by default as identity primary key,
  email text unique not null, name text, phone text, sms_opt_in boolean not null default false,
  source text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create or replace function public.crm_submit_contact(
  p_email text, p_name text default null, p_phone text default null, p_sms_opt_in boolean default false,
  p_source text default null, p_metadata jsonb default '{}'::jsonb
) returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.crm_contacts(email,name,phone,sms_opt_in,source,metadata)
  values(lower(trim(p_email)),p_name,p_phone,p_sms_opt_in,p_source,coalesce(p_metadata,'{}'::jsonb))
  on conflict(email) do update set
    name=coalesce(excluded.name, crm_contacts.name), phone=coalesce(excluded.phone, crm_contacts.phone),
    sms_opt_in=excluded.sms_opt_in, source=coalesce(excluded.source, crm_contacts.source),
    metadata=crm_contacts.metadata || excluded.metadata, updated_at=now();
end $$;

grant execute on function public.crm_submit_contact(text,text,text,boolean,text,jsonb) to anon, authenticated;

-- RLS: public market/research data is readable; only service role writes it.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['tickers','quotes','market_snapshots','market_movers','analysis_runs','signals','contract_candidates','risk_assessments','news_items','filings','transcript_statements','sentiment_readings','economic_events','earnings_events','signal_updates','signal_feed_events','ohlcv_bars','provider_configs','lit_constructs','lit_studies','lit_construct_studies']
  LOOP
    EXECUTE format('alter table public.%I enable row level security', t);
    EXECUTE format('drop policy if exists %I on public.%I', 'public read', t);
    EXECUTE format('create policy %I on public.%I for select using (true)', 'public read', t);
  END LOOP;
END $$;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['user_prefs','watchlists','paper_trades','trade_plans','trade_modifications','behavioral_observations','behavioral_prefs','usage_costs','ai_chat_messages']
  LOOP
    EXECUTE format('alter table public.%I enable row level security', t);
    EXECUTE format('drop policy if exists %I on public.%I', 'own rows', t);
    EXECUTE format('create policy %I on public.%I for all using (user_id = auth.uid()) with check (user_id = auth.uid())', 'own rows', t);
  END LOOP;
END $$;

alter table public.crm_contacts enable row level security;
-- no client read policy by design; signup RPC is SECURITY DEFINER.
