-- Canonical brokerage-read and TradeCycle episode infrastructure.
-- This is provider-neutral and intentionally read-only: brokerages execute trades;
-- URSORA ingests account activity, reconstructs position episodes, and analyzes them.

create table if not exists public.broker_connections (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  provider_key text not null,
  external_connection_id text,
  display_name text,
  status text not null default 'pending',
  access_mode text not null default 'read_only',
  auth_method text,
  last_synced_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, provider_key, external_connection_id)
);

create table if not exists public.brokerage_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  connection_id bigint not null references public.broker_connections(id) on delete cascade,
  external_account_id text not null,
  account_name text,
  account_type text,
  account_mask text,
  currency text,
  status text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(connection_id, external_account_id)
);

create table if not exists public.broker_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  account_id bigint not null references public.brokerage_accounts(id) on delete cascade,
  external_order_id text not null,
  symbol text,
  asset_type text,
  option_type text,
  strike numeric,
  expiration date,
  side text,
  position_effect text,
  quantity numeric,
  filled_quantity numeric,
  average_fill_price numeric,
  status text,
  order_type text,
  submitted_at timestamptz,
  filled_at timestamptz,
  provider_updated_at timestamptz,
  raw_source jsonb not null default '{}'::jsonb,
  retrieved_at timestamptz not null default now(),
  unique(account_id, external_order_id)
);

create table if not exists public.broker_activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  account_id bigint not null references public.brokerage_accounts(id) on delete cascade,
  external_activity_id text,
  activity_type text not null,
  symbol text,
  asset_type text,
  option_type text,
  strike numeric,
  expiration date,
  side text,
  quantity numeric,
  price numeric,
  amount numeric,
  fee numeric,
  currency text,
  occurred_at timestamptz,
  occurred_date date,
  timestamp_precision text not null default 'unknown',
  raw_source jsonb not null default '{}'::jsonb,
  retrieved_at timestamptz not null default now()
);

create unique index if not exists broker_activities_external_unique
  on public.broker_activities(account_id, external_activity_id)
  where external_activity_id is not null;

create index if not exists broker_orders_account_symbol_time_idx
  on public.broker_orders(account_id, symbol, coalesce(filled_at, submitted_at) desc);

create index if not exists broker_activities_account_symbol_time_idx
  on public.broker_activities(account_id, symbol, coalesce(occurred_at, occurred_date::timestamptz) desc);

create table if not exists public.trade_episodes (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  account_id bigint references public.brokerage_accounts(id) on delete set null,
  symbol text not null,
  asset_type text,
  option_type text,
  strike numeric,
  expiration date,
  status text not null default 'open',
  exposure_direction text,
  opening_quantity numeric,
  current_quantity numeric,
  average_entry_price numeric,
  average_exit_price numeric,
  opened_at timestamptz,
  closed_at timestamptz,
  realized_pl numeric,
  realized_return_pct numeric,
  source_mode text not null default 'brokerage_sync',
  source_provider text,
  external_episode_key text,
  thesis_direction text,
  thesis_inference_basis text,
  thesis_state text,
  thesis_support numeric,
  thesis_agreement numeric,
  thesis_last_checked_at timestamptz,
  review_status text,
  review_summary text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists trade_episodes_external_key_unique
  on public.trade_episodes(user_id, source_provider, external_episode_key)
  where external_episode_key is not null;

create index if not exists trade_episodes_user_symbol_status_idx
  on public.trade_episodes(user_id, symbol, status, coalesce(opened_at, created_at) desc);

create table if not exists public.trade_episode_orders (
  episode_id bigint not null references public.trade_episodes(id) on delete cascade,
  order_id bigint not null references public.broker_orders(id) on delete cascade,
  role text,
  primary key (episode_id, order_id)
);

create table if not exists public.position_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  episode_id bigint not null references public.trade_episodes(id) on delete cascade,
  quantity numeric,
  average_cost numeric,
  market_price numeric,
  market_value numeric,
  unrealized_pl numeric,
  captured_at timestamptz not null,
  source_name text,
  raw_source jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists position_snapshots_episode_time_idx
  on public.position_snapshots(episode_id, captured_at);

create table if not exists public.tradecycle_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  episode_id bigint not null references public.trade_episodes(id) on delete cascade,
  signal_id bigint references public.signals(id) on delete set null,
  event_type text not null,
  materiality text,
  thesis_direction text,
  thesis_state text,
  thesis_support numeric,
  directional_agreement numeric,
  underlying_price numeric,
  position_quantity numeric,
  evidence jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists tradecycle_events_episode_time_idx
  on public.tradecycle_events(episode_id, occurred_at);

-- Read/write policies are always scoped to the authenticated owner. Service-role sync
-- functions can normalize provider data without exposing provider credentials client-side.
alter table public.broker_connections enable row level security;
alter table public.brokerage_accounts enable row level security;
alter table public.broker_orders enable row level security;
alter table public.broker_activities enable row level security;
alter table public.trade_episodes enable row level security;
alter table public.trade_episode_orders enable row level security;
alter table public.position_snapshots enable row level security;
alter table public.tradecycle_events enable row level security;

drop policy if exists broker_connections_own on public.broker_connections;
create policy broker_connections_own on public.broker_connections for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists brokerage_accounts_own on public.brokerage_accounts;
create policy brokerage_accounts_own on public.brokerage_accounts for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists broker_orders_own on public.broker_orders;
create policy broker_orders_own on public.broker_orders for select
using (auth.uid() = user_id);

drop policy if exists broker_activities_own on public.broker_activities;
create policy broker_activities_own on public.broker_activities for select
using (auth.uid() = user_id);

drop policy if exists trade_episodes_own on public.trade_episodes;
create policy trade_episodes_own on public.trade_episodes for select
using (auth.uid() = user_id);

drop policy if exists trade_episode_orders_own on public.trade_episode_orders;
create policy trade_episode_orders_own on public.trade_episode_orders for select
using (
  exists (
    select 1 from public.trade_episodes e
    where e.id = episode_id and e.user_id = auth.uid()
  )
);

drop policy if exists position_snapshots_own on public.position_snapshots;
create policy position_snapshots_own on public.position_snapshots for select
using (auth.uid() = user_id);

drop policy if exists tradecycle_events_own on public.tradecycle_events;
create policy tradecycle_events_own on public.tradecycle_events for select
using (auth.uid() = user_id);
