create table if not exists public.market_cycle_states (
  symbol text primary key references public.tickers(symbol) on delete cascade,
  timeframe text not null default '30m',
  cycle_state text not null default 'unconfirmed',
  direction text not null default 'neutral',
  event_type text not null default 'unconfirmed',
  reversal_origin numeric,
  confirmation_price numeric,
  confirmation_at timestamptz,
  retest_price numeric,
  retest_at timestamptz,
  retest_status text not null default 'not_observed',
  cycle_invalidation numeric,
  volume_confirmation_ratio numeric,
  range_position_5d numeric,
  range_position_20d numeric,
  move_extension numeric,
  bars_since_confirmation integer,
  confidence_score numeric,
  reason text,
  source_bar_time timestamptz,
  source_retrieved_at timestamptz,
  computed_at timestamptz not null default now(),
  details jsonb not null default '{}'::jsonb,
  constraint market_cycle_states_direction_check check (direction in ('bullish','bearish','neutral')),
  constraint market_cycle_states_retest_check check (retest_status in ('held','failed','pending','not_observed'))
);

create index if not exists market_cycle_states_computed_idx
  on public.market_cycle_states(computed_at desc);

create index if not exists market_cycle_states_direction_idx
  on public.market_cycle_states(direction, cycle_state);

alter table public.market_cycle_states enable row level security;

drop policy if exists "authenticated read market cycle states" on public.market_cycle_states;
create policy "authenticated read market cycle states"
  on public.market_cycle_states for select
  to authenticated
  using (true);

create table if not exists public.market_cycle_state_history (
  id bigint generated by default as identity primary key,
  symbol text not null references public.tickers(symbol) on delete cascade,
  timeframe text not null,
  cycle_state text not null,
  direction text not null,
  event_type text not null,
  reversal_origin numeric,
  confirmation_price numeric,
  confirmation_at timestamptz,
  retest_price numeric,
  retest_at timestamptz,
  retest_status text not null,
  cycle_invalidation numeric,
  volume_confirmation_ratio numeric,
  range_position_5d numeric,
  range_position_20d numeric,
  move_extension numeric,
  bars_since_confirmation integer,
  confidence_score numeric,
  reason text,
  source_bar_time timestamptz,
  source_retrieved_at timestamptz,
  computed_at timestamptz not null default now(),
  details jsonb not null default '{}'::jsonb
);

create index if not exists market_cycle_state_history_symbol_idx
  on public.market_cycle_state_history(symbol, computed_at desc);

alter table public.market_cycle_state_history enable row level security;

drop policy if exists "authenticated read market cycle history" on public.market_cycle_state_history;
create policy "authenticated read market cycle history"
  on public.market_cycle_state_history for select
  to authenticated
  using (true);
