-- TradeCycle lifecycle: suggestion, monitoring, and post-trade review.
-- Keeps directional thesis validation separate from execution/P&L.

alter table public.paper_trades
  add column if not exists thesis_mode text,
  add column if not exists inferred_thesis_direction text,
  add column if not exists thesis_inference_basis text,
  add column if not exists thesis_status text,
  add column if not exists thesis_support numeric,
  add column if not exists thesis_agreement numeric,
  add column if not exists thesis_last_checked_at timestamptz,
  add column if not exists thesis_review_status text,
  add column if not exists thesis_review_summary text;

create table if not exists public.tradecycle_thesis_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  trade_id bigint not null references public.paper_trades(id) on delete cascade,
  signal_id bigint references public.signals(id) on delete set null,
  event_type text not null,
  thesis_direction text,
  thesis_state text,
  thesis_support numeric,
  directional_agreement numeric,
  underlying_price numeric,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists tradecycle_thesis_events_trade_created_idx
  on public.tradecycle_thesis_events(trade_id, created_at desc);

alter table public.tradecycle_thesis_events enable row level security;

drop policy if exists tradecycle_thesis_events_select_own on public.tradecycle_thesis_events;
create policy tradecycle_thesis_events_select_own
on public.tradecycle_thesis_events for select
using (auth.uid() = user_id);

drop policy if exists tradecycle_thesis_events_insert_own on public.tradecycle_thesis_events;
create policy tradecycle_thesis_events_insert_own
on public.tradecycle_thesis_events for insert
with check (auth.uid() = user_id);
