begin;

create table if not exists public.snaptrade_trade_episodes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  account_id text not null references public.snaptrade_accounts(id) on delete cascade,
  external_episode_key text not null,
  symbol text not null,
  option_symbol text,
  asset_type text not null,
  option_type text,
  strike numeric,
  expiration date,
  status text not null check (status in ('open','closed')),
  exposure_side text not null check (exposure_side in ('long','short')),
  direction text not null default 'neutral',
  quantity numeric not null,
  average_entry_price numeric,
  average_exit_price numeric,
  opened_at timestamptz not null,
  closed_at timestamptz,
  session_date date not null,
  realized_pl numeric,
  realized_return_pct numeric,
  entry_activity_ids text[] not null default '{}',
  exit_activity_ids text[] not null default '{}',
  timestamp_precision text not null default 'provider',
  raw_summary jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  unique(user_id, external_episode_key)
);

create index if not exists snaptrade_trade_episodes_user_opened_idx
  on public.snaptrade_trade_episodes(user_id, opened_at desc);

create index if not exists snaptrade_trade_episodes_user_symbol_idx
  on public.snaptrade_trade_episodes(user_id, symbol, opened_at desc);

alter table public.snaptrade_trade_episodes enable row level security;

drop policy if exists "users read own snaptrade trade episodes" on public.snaptrade_trade_episodes;
create policy "users read own snaptrade trade episodes"
on public.snaptrade_trade_episodes for select
using (auth.uid() = user_id);

commit;
