-- URSORA TradeCycle v2: normalized option-market snapshots
-- This table stores the provider observations used by the thesis engine so
-- option evidence can be audited independently from generated signals.

create table if not exists public.option_market_snapshots (
  id bigint generated by default as identity primary key,
  underlying_symbol text not null,
  option_symbol text not null,
  instrument_id text,
  option_type text not null check (option_type in ('CALL','PUT')),
  strike numeric not null,
  expiration date not null,
  price numeric,
  bid numeric,
  ask numeric,
  volume numeric,
  open_interest numeric,
  implied_volatility numeric,
  delta numeric,
  gamma numeric,
  theta numeric,
  vega numeric,
  spread_pct numeric,
  retrieved_at timestamptz not null default now(),
  source_name text not null default 'Webull PaperTrade Sandbox',
  is_demo boolean not null default true
);

create index if not exists option_market_snapshots_underlying_time_idx
  on public.option_market_snapshots (underlying_symbol, retrieved_at desc);

create index if not exists option_market_snapshots_contract_time_idx
  on public.option_market_snapshots (option_symbol, retrieved_at desc);

alter table public.option_market_snapshots enable row level security;

drop policy if exists "authenticated users can read option market snapshots" on public.option_market_snapshots;
create policy "authenticated users can read option market snapshots"
  on public.option_market_snapshots
  for select
  to authenticated
  using (true);

comment on table public.option_market_snapshots is
  'Timestamped option-chain observations used by URSORA TradeCycle scoring. Service-role Edge Functions write; authenticated users may read.';
